apiVersion: v1
kind: Service
metadata:
  name: react-app  # Name of the service (used in Ingress or DNS if needed)
spec:
  selector:
    app: react-app  # This must match the label on your Deployment
  ports:
    - protocol: TCP
      port: 80          # Exposed port (what clients connect to)
      targetPort: 80    # Container's port (what NGINX inside the pod listens on)
  type: LoadBalancer     # Makes the service accessible **externally** with a public IP (on AKS)
